"""Security gate for Docker Compose documents, from templates AND from the LLM.

Nothing reaches the workspace or the Docker engine without passing
`validate_compose()`. It layers three independent checks:

1. Explicit deny rules with actionable messages (privileged mode, host
   namespaces, published ports, Docker socket...).
2. A strict allow-list schema: every model uses `extra="forbid"`, so any Compose
   key EnvCrafter does not explicitly support is rejected. New or exotic Compose
   features are denied by default instead of slipping through a blocklist.
3. Semantic checks the schema cannot express: image allow-list, volume sources,
   network usage, `${VAR}` interpolation, service references.

The input is a *source* document: logical networks (`internal`, `egress`), no
names, no Traefik labels. The renderer (workspace/renderer.py) adds those
afterwards, from trusted code only.
"""

import re
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Annotated, Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    StringConstraints,
    ValidationError,
)

from app.policy.images import ImageAllowlist, ImageRefError, parse_image_ref

MAX_SERVICES = 12
MAX_VOLUMES = 16

# Variables the renderer always writes to the project's .env file.
BUILTIN_VARIABLES = frozenset({"EC_PROJECT", "EC_HOSTNAME", "EC_TZ"})


@dataclass(frozen=True)
class PolicyViolation:
    location: str
    message: str

    def __str__(self) -> str:
        return f"{self.location}: {self.message}"


class ComposePolicyError(ValueError):
    def __init__(self, violations: list[PolicyViolation]) -> None:
        super().__init__("; ".join(str(v) for v in violations))
        self.violations = violations


@dataclass(frozen=True)
class PolicyContext:
    allowlist: ImageAllowlist
    # Outbound Internet is opt-in per stack (and never granted to vulnerable labs).
    allow_egress: bool
    # Names of the per-project secrets that `${NAME}` may reference.
    secret_names: frozenset[str] = frozenset()


# --- 1. Explicit deny rules -----------------------------------------------------

_DENIED_TOP_LEVEL: dict[str, str] = {
    "name": "the project name is generated by EnvCrafter",
    "networks": "networks are generated by EnvCrafter; use `internal` or `egress` on services",
    "secrets": "secrets are generated per project by EnvCrafter",
    "configs": "configs are not supported",
    "include": "including other Compose files is not allowed",
    "version": "obsolete field, remove it",
}

_DENIED_SERVICE_KEYS: dict[str, str] = {
    "privileged": "privileged containers can take over the host",
    "cap_add": "adding Linux capabilities is not allowed",
    "devices": "mapping host devices is not allowed",
    "device_cgroup_rules": "device cgroup rules are not allowed",
    "network_mode": "services must only use EnvCrafter-managed networks",
    "pid": "sharing a PID namespace is not allowed",
    "ipc": "sharing an IPC namespace is not allowed",
    "uts": "sharing the UTS namespace is not allowed",
    "userns_mode": "changing the user namespace mode is not allowed",
    "cgroup": "changing the cgroup namespace is not allowed",
    "cgroup_parent": "changing the cgroup parent is not allowed",
    "sysctls": "kernel parameters cannot be changed",
    "runtime": "alternative container runtimes are not allowed",
    "ports": "host ports are never published; web UIs are routed through Traefik",
    "extra_hosts": "overriding name resolution is not allowed",
    "dns": "overriding DNS servers is not allowed",
    "dns_search": "overriding DNS search domains is not allowed",
    "links": "legacy links are not allowed; use service names on shared networks",
    "external_links": "linking to containers outside the project is not allowed",
    "volumes_from": "mounting another container's volumes is not allowed",
    "build": "building images is not allowed; use an allow-listed image",
    "container_name": "container names are generated by EnvCrafter",
    "env_file": "environment files are generated by EnvCrafter",
    "group_add": "adding supplementary groups is not allowed",
    "oom_kill_disable": "disabling the OOM killer is not allowed",
    "extends": "extending other services is not allowed",
}

_ALLOWED_SECURITY_OPTS = frozenset({"no-new-privileges:true", "no-new-privileges=true"})
_RESERVED_LABEL_PREFIXES = ("traefik.", "envcrafter.", "com.docker.")
_DENIED_VOLUME_KEYS = ("driver", "driver_opts", "external", "name")
# A named volume with `driver_opts: {type: none, o: bind, device: /}` is a
# host bind mount in disguise: volume drivers are never configurable.

_DOCKER_SOCKET_MARKERS = (
    "docker.sock",
    "docker_engine",
    "/var/run/docker",
    "containerd.sock",
    "podman.sock",
)


# --- 2. Allow-list schema -------------------------------------------------------


class _ComposeModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


ServiceName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9-]{0,39}$")]
VolumeName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_-]{0,39}$")]
LogicalNetwork = Literal["internal", "egress"]
EnvKey = Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")]
EnvValue = StrictStr | StrictInt | StrictFloat | StrictBool | None
ContainerPath = Annotated[str, StringConstraints(pattern=r"^/[A-Za-z0-9._/-]*$", max_length=255)]
Duration = Annotated[str, StringConstraints(pattern=r"^(\d+(ms|s|m|h))+$")]
ByteSize = Annotated[str, StringConstraints(pattern=r"^\d+[bkmgBKMG]?$")]
UserSpec = Annotated[
    str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{1,32}(:[A-Za-z0-9_-]{1,32})?$")
]
Capability = Annotated[str, StringConstraints(pattern=r"^[A-Z_]{2,32}$")]


class Healthcheck(_ComposeModel):
    test: list[StrictStr] | StrictStr
    interval: Duration | None = None
    timeout: Duration | None = None
    retries: StrictInt | None = None
    start_period: Duration | None = None
    start_interval: Duration | None = None


class DependsOnEntry(_ComposeModel):
    condition: Literal["service_started", "service_healthy", "service_completed_successfully"] = (
        "service_started"
    )
    restart: StrictBool | None = None


class VolumeMount(_ComposeModel):
    type: Literal["volume", "bind", "tmpfs"]
    source: StrictStr | None = None
    target: ContainerPath
    read_only: StrictBool | None = None


class Service(_ComposeModel):
    image: StrictStr
    command: StrictStr | list[StrictStr] | None = None
    environment: dict[EnvKey, EnvValue] | None = None
    volumes: list[StrictStr | VolumeMount] = Field(default_factory=list)
    networks: list[LogicalNetwork] = Field(default_factory=list)
    depends_on: list[ServiceName] | dict[ServiceName, DependsOnEntry] | None = None
    healthcheck: Healthcheck | None = None
    restart: Literal["no", "always", "on-failure", "unless-stopped"] | None = None
    user: UserSpec | None = None
    working_dir: ContainerPath | None = None
    read_only: StrictBool | None = None
    tmpfs: list[ContainerPath] | None = None
    security_opt: list[StrictStr] | None = None
    cap_drop: list[Capability] | None = None
    init: StrictBool | None = None
    stop_grace_period: Duration | None = None
    shm_size: ByteSize | None = None
    mem_limit: ByteSize | None = None
    pids_limit: StrictInt | None = None
    labels: dict[StrictStr, StrictStr] | None = None
    hostname: ServiceName | None = None


class TopLevelVolume(_ComposeModel):
    """Named volumes carry no options at all (see _DENIED_VOLUME_KEYS)."""


class ComposeSpec(_ComposeModel):
    services: dict[ServiceName, Service] = Field(min_length=1, max_length=MAX_SERVICES)
    volumes: dict[VolumeName, TopLevelVolume | None] = Field(
        default_factory=dict, max_length=MAX_VOLUMES
    )


# --- Entry point ----------------------------------------------------------------


def validate_compose(document: object, context: PolicyContext) -> ComposeSpec:
    """Return the validated spec, or raise ComposePolicyError listing every violation."""
    if not isinstance(document, dict):
        raise ComposePolicyError([PolicyViolation("$", "a Compose document must be a mapping")])

    violations = [
        *_check_denied_keys(document),
        *_check_docker_socket(document),
        *_check_interpolation(document, context),
    ]
    if violations:
        raise ComposePolicyError(violations)

    try:
        spec = ComposeSpec.model_validate(document)
    except ValidationError as exc:
        raise ComposePolicyError(
            [
                PolicyViolation(
                    ".".join(str(part) for part in error["loc"]) or "$",
                    "unsupported key" if error["type"] == "extra_forbidden" else error["msg"],
                )
                for error in exc.errors()
            ]
        ) from None

    violations = list(_check_semantics(spec, context))
    if violations:
        raise ComposePolicyError(violations)
    return spec


# --- Checks -------------------------------------------------------------------


def _check_denied_keys(document: dict[Any, Any]) -> Iterator[PolicyViolation]:
    for key in document:
        if key in _DENIED_TOP_LEVEL:
            yield PolicyViolation(str(key), _DENIED_TOP_LEVEL[key])
        elif isinstance(key, str) and key.startswith("x-"):
            yield PolicyViolation(key, "extension fields are not allowed")

    services = document.get("services")
    if isinstance(services, dict):
        for name, service in services.items():
            if not isinstance(service, dict):
                continue
            for key, message in _DENIED_SERVICE_KEYS.items():
                if key in service:
                    yield PolicyViolation(f"services.{name}.{key}", message)
            for option in service.get("security_opt") or []:
                if option not in _ALLOWED_SECURITY_OPTS:
                    yield PolicyViolation(
                        f"services.{name}.security_opt",
                        f"only no-new-privileges is allowed, got {option!r}",
                    )
            labels = service.get("labels")
            label_keys = labels.keys() if isinstance(labels, dict) else []
            for label in label_keys:
                if isinstance(label, str) and label.startswith(_RESERVED_LABEL_PREFIXES):
                    yield PolicyViolation(
                        f"services.{name}.labels.{label}", "this label namespace is reserved"
                    )

    volumes = document.get("volumes")
    if isinstance(volumes, dict):
        for name, config in volumes.items():
            if isinstance(config, dict):
                for key in _DENIED_VOLUME_KEYS:
                    if key in config:
                        yield PolicyViolation(
                            f"volumes.{name}.{key}", "volume options are not configurable"
                        )


def _walk_strings(node: object, path: str = "$") -> Iterator[tuple[str, str]]:
    if isinstance(node, str):
        yield path, node
    elif isinstance(node, dict):
        for key, value in node.items():
            yield from _walk_strings(value, f"{path}.{key}" if path != "$" else str(key))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            yield from _walk_strings(value, f"{path}[{index}]")


def _check_docker_socket(document: dict[Any, Any]) -> Iterator[PolicyViolation]:
    # Defence in depth: whatever the field (volume, env, command...), a stack
    # that even mentions the Docker socket is rejected.
    for path, value in _walk_strings(document):
        lowered = value.lower()
        if any(marker in lowered for marker in _DOCKER_SOCKET_MARKERS):
            yield PolicyViolation(path, "references to the container engine socket are forbidden")


_INTERPOLATION_RE = re.compile(r"\$(?:\{(?P<braced>[^}]*)\}|(?P<bare>[A-Za-z_][A-Za-z0-9_]*))")
_VARIABLE_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# `${VAR}` is only meaningful in these fields; in images, volumes or labels it
# could smuggle a value past the checks above.
_INTERPOLATION_FIELDS_RE = re.compile(
    r"^services\.[^.]+\.(environment\.[^.]+|command(\[\d+\])?|healthcheck\.test(\[\d+\])?)$"
)


def _check_interpolation(
    document: dict[Any, Any], context: PolicyContext
) -> Iterator[PolicyViolation]:
    allowed_names = BUILTIN_VARIABLES | context.secret_names
    for path, value in _walk_strings(document):
        text = value.replace("$$", "")  # `$$` is Compose's escape for a literal `$`
        if "$" not in text:
            continue
        if not _INTERPOLATION_FIELDS_RE.match(path):
            yield PolicyViolation(path, "variable interpolation is not allowed in this field")
            continue
        matches = list(_INTERPOLATION_RE.finditer(text))
        if text.count("$") != len(matches):
            yield PolicyViolation(path, "malformed variable interpolation (escape `$` as `$$`)")
            continue
        for match in matches:
            name = match.group("braced") or match.group("bare") or ""
            if not _VARIABLE_NAME_RE.match(name):
                yield PolicyViolation(
                    path, "interpolation modifiers (`:-`, `:?`...) are not allowed"
                )
            elif name not in allowed_names:
                yield PolicyViolation(path, f"unknown variable ${{{name}}}")


_BIND_SOURCE_RE = re.compile(r"^\./[A-Za-z0-9._-]+(/[A-Za-z0-9._-]+)*$")
_VOLUME_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]{0,39}$")


def _check_semantics(spec: ComposeSpec, context: PolicyContext) -> Iterator[PolicyViolation]:
    for name, service in spec.services.items():
        where = f"services.{name}"

        allowed = None
        try:
            image = parse_image_ref(service.image)
        except ImageRefError as exc:
            yield PolicyViolation(f"{where}.image", str(exc))
        else:
            allowed = context.allowlist.find(image)
            if allowed is None:
                yield PolicyViolation(f"{where}.image", f"{image} is not on the image allow-list")

        if "egress" in service.networks:
            if not context.allow_egress:
                yield PolicyViolation(
                    f"{where}.networks", "outbound Internet access is not allowed for this stack"
                )
            elif allowed is not None and allowed.vulnerable:
                yield PolicyViolation(
                    f"{where}.networks", "intentionally vulnerable images never get Internet access"
                )

        dependencies = (
            service.depends_on
            if isinstance(service.depends_on, list)
            else list((service.depends_on or {}).keys())
        )
        for dependency in dependencies:
            if dependency == name or dependency not in spec.services:
                yield PolicyViolation(f"{where}.depends_on", f"unknown service {dependency!r}")

        for index, volume in enumerate(service.volumes):
            yield from _check_volume(f"{where}.volumes[{index}]", volume, spec)


def _check_volume(
    where: str, volume: str | VolumeMount, spec: ComposeSpec
) -> Iterator[PolicyViolation]:
    if isinstance(volume, VolumeMount):
        kind, source = volume.type, volume.source
    else:
        parts = volume.split(":")
        if len(parts) > 3:
            yield PolicyViolation(where, "malformed volume entry")
            return
        if len(parts) == 3 and parts[2] not in {"ro", "rw"}:
            yield PolicyViolation(where, "volume mode must be `ro` or `rw`")
        if len(parts) >= 2 and not re.match(r"^/[A-Za-z0-9._/-]*$", parts[1]):
            yield PolicyViolation(where, "the container path must be absolute")
        source = parts[0] if len(parts) >= 2 else None
        kind = "bind" if source is not None and not _VOLUME_NAME_RE.match(source) else "volume"

    if source is None:  # anonymous volume or tmpfs
        return
    if kind == "volume" and source not in spec.volumes:
        yield PolicyViolation(where, f"named volume {source!r} is not declared")
    elif kind == "bind" and (not _BIND_SOURCE_RE.match(source) or ".." in source.split("/")):
        yield PolicyViolation(
            where, "bind mounts must stay inside the project workspace (./relative/path)"
        )
